[package]
name = "websub-sub"
version = "0.1.0"
authors = ["Daiki Mizukami <tesaguriguma@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
atom = { version = "0.8", package = "atom_syndication" }
base64 = "0.11"
diesel = { version = "1.4.3", default-features = false, features = ["r2d2", "sqlite"] }
structopt = "0.3.0"
futures = "0.3.0"
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.6"
tower-service = "0.3"
hex = "0.4"
hmac = "0.7"
http = "0.2"
hyper = { version = "0.13.0", features = ["stream"] }
hyper-tls = "0.4"
mime = "0.3"
rand = "0.7"
rss = "1"
sha-1 = "0.8"
tokio = { version = "0.2.0", features = ["macros", "stream", "tcp", "time", "uds"] }
libsqlite3-sys = { version = ">=0.8.0, <0.17.0", optional = true }

[features]
openssl-vendored = ["hyper-tls/vendored"]
sqlite-bundled = ["libsqlite3-sys/bundled"]
